### ISSUE TITLE
Add flexbox tachyon classes

### ISSUE THREAD

**Issue by jrah** [madbitco/madsauce#4]
This is related to #3.

More frequently I have found that I wanted to quickly use Flexbox and it would be helpful to have that as CSS classes ready immediately. Here's what I am thinking:

```scss
.fb {
  @include flexbox;
}

.fd-c {
  @include flex-direction(column);
  @each $mqs, $size in $mqs {
    @include mq(#{$size}) {
      &-#{$mqs} {
        @include flex-direction(column);
      }
    }
  }
}

.fd-r {
  @include flex-direction(row);
  @each $mqs, $size in $mqs {
    @include mq(#{$size}) {
      &-#{$mqs} {
        @include flex-direction(row);
      }
    }
  }
}

.jc-c {
  @include justify-content(center);
  @each $mqs, $size in $mqs {
    @include mq(#{$size}) {
      &-#{$mqs} {
        @include justify-content(center);
      }
    }
  }
}
```

**Comment by matthewmorek** [comment]
@jrah Feel free to submit a PR with this change set, and I'll happily merge it. Although, does it make sense if we can just hook this repo to `tachyons-sass` directly and just add our opinionated defaults on top of it? Let's not create a new standard, shall we? 😄

**Comment by jrah** [comment]
I have been using tachyons-sass recently and would agree with this! Closing this for now.
